"""LanceDB store wrapper: open/create the chunks table + BM25 FTS index."""
from __future__ import annotations

import re
import threading
import time
from typing import Iterable

import lancedb
import pyarrow as pa

from src.core.logging import logger
from src.core.paths import lancedb_path
from src.storage.identifiers import safe_identifier as _safe_identifier  # noqa: F401 — re-exported for tests
from src.storage.identifiers import safe_identifier
from src.storage.schema import LANCEDB_SCHEMA, TABLE_NAME, ChunkRecord


# Path-keyed singleton: the connection is opened against the user-data
# directory, which can change between test runs (set ``URAG_DATA_DIR`` via
# Settings to a tmp dir). We cache by resolved path so different tests get
# different connections but the same path within a test reuses one.
_db_lock = threading.Lock()
_db_by_path: dict[str, "lancedb.DBConnection"] = {}
_current_db: "lancedb.DBConnection | None" = None
_current_path: str | None = None


# ----------------------------------------------------------------------
# Reverse index: doc_id <-> thread_id
# ----------------------------------------------------------------------
# Why this exists
# ----------------
# The previous ``GET /sessions`` endpoint called
# ``list_documents(thread_id=tid)`` inside a ``for tid in aggregated``
# loop. Each call did a full ``table.to_arrow()`` scan + Python group-by
# — classic N+1. With 50 sessions this was 50 scans, each 30-200 ms,
# making the endpoint take 2-10 s on a populated corpus.
#
# The reverse index collapses those N scans into one. It maps:
#   doc_id -> set of thread_ids that own at least one chunk of this doc
#   thread_id -> set of doc_ids visible to that thread
#   thread_id -> first filename seen (for /sessions title fallback)
#
# The index is built lazily on first call to
# :func:`count_documents_by_threads` (one scan), and maintained
# incrementally on every add_chunks / delete_by_doc_id /
# delete_by_thread_id so subsequent calls are pure dict reads. Per-
# thread cache invalidation is now SCOPED (only the affected thread),
# so unrelated threads keep their cached ``list_documents`` results.
#
# Thread safety: every mutation is protected by ``_reverse_index_lock``
# so a concurrent ``/sessions`` reader and a background uploader can't
# observe a half-updated index.
_doc_to_threads: dict[str, set[str]] = {}
_thread_to_docs: dict[str, set[str]] = {}
_thread_first_filename: dict[str, str] = {}
# v2.0.6 P2-1 — tracks the most recent ``ingested_at`` per thread so
# ``GET /sessions`` can populate ``updated_at`` for doc-only threads
# (threads that uploaded docs but never sent a message and therefore
# have no LangGraph checkpoint). ISO 8601 with ``Z`` suffix → string
# ``max`` gives chronological max.
_thread_latest_ingested_at: dict[str, str] = {}
_reverse_index_lock = threading.Lock()


def get_db() -> lancedb.DBConnection:
    """Singleton LanceDB connection rooted at the user data dir.

    Threading contract: connection setup is serialized with a lock so two
    threads racing on a cold cache don't both call ``lancedb.connect`` —
    which has been observed to clobber the on-disk state on some versions.
    After the first connect, callers take the fast path with no lock.
    """
    global _current_db, _current_path
    path = str(lancedb_path())
    if _current_path == path and _current_db is not None:
        return _current_db
    with _db_lock:
        if _current_path == path and _current_db is not None:
            return _current_db
        cached = _db_by_path.get(path)
        if cached is not None:
            _current_db = cached
            _current_path = path
            return cached
        logger.info(f"Opening LanceDB connection at {path}")
        db = lancedb.connect(path)
        _db_by_path[path] = db
        _current_db = db
        _current_path = path
        return db


def reset_for_tests() -> None:
    """Reset cached connections. Tests only."""
    global _current_db, _current_path, _db_by_path
    _current_db = None
    _current_path = None
    _db_by_path = {}
    # Drop the per-thread doc-listing cache so consecutive test runs
    # don't see stale entries from prior threads.
    invalidate_thread_doc_cache()
    # v2.0.7 perf-3: also drop the chunk-list cache.
    invalidate_thread_chunk_cache()
    # Also drop the reverse index — it's path-keyed (every test that
    # changes ``RAG_DATA_DIR`` gets a fresh LanceDB instance, so the
    # old doc->thread edges are stale).
    _doc_to_threads.clear()
    _thread_to_docs.clear()
    _thread_first_filename.clear()
    _thread_latest_ingested_at.clear()


# doc_id is generated by ``utils.ids.new_id`` which produces a UUID4
# (32 hex chars + dashes, e.g. ``abc12345-1234-5678-9abc-def012345678``).
# P2-1: identifier validation moved to :mod:`src.storage.identifiers`.
# The banned-chars set below used to live here next to the implementation;
# now it's gone (the public ``safe_identifier`` lives in identifiers.py
# and uses a single canonical regex). This module re-exports the public
# name under the old underscore alias for tests that still import it.


def _table_names(db: lancedb.DBConnection) -> list[str]:
    """Robustly extract table names from any lancedb version."""
    try:
        result = db.list_tables()
        if hasattr(result, "tables"):
            return list(result.tables)
        return list(result)
    except AttributeError:
        return list(db.table_names())


def get_table(create_if_missing: bool = True):
    """Return the chunks table, creating it (and the FTS index) if needed.

    Performs a best-effort one-shot migration: if the existing table lacks
    the ``thread_id`` column (added in the multi-conversation extension),
    call ``add_columns`` and backfill empty strings. Failure here is logged
    and ignored — legacy tables stay un-scoped rather than broken.
    """
    db = get_db()
    if TABLE_NAME in _table_names(db):
        table = db.open_table(TABLE_NAME)
        _maybe_add_thread_id_column(table)
        # v2.0.29.4 (Phase 4 PR-2) — temporal expiry migration.
        # Idempotent: pre-PR-2 tables get the column added + NULL
        # backfill (treated as "no expiry"); new tables start with the
        # column from the LANCEDB_SCHEMA definition.
        _maybe_add_expires_at_column(table)
        return table
    if not create_if_missing:
        raise KeyError(f"Table {TABLE_NAME!r} does not exist")
    logger.info(f"Creating LanceDB table {TABLE_NAME!r}")
    # LanceDB requires at least one row to infer types; provide a dummy row
    # with all required fields populated, then delete it after FTS is set up.
    dummy = pa.table(
        {
            "chunk_id": ["__bootstrap__"],
            "doc_id": ["__bootstrap__"],
            "text": [""],
            "vector": [[0.0] * 1024],
            "sparse": ["{}"],
            "filename": [""],
            "source_type": ["bootstrap"],
            "source_path": [""],
            "mime_type": [""],
            "chunk_index": pa.array([0], type=pa.int32()),
            "chunk_type": [""],
            "page_number": pa.array([0], type=pa.int32()),
            "section": [""],
            "sheet": [""],
            "headers": pa.array([[]], type=pa.list_(pa.string())),
            "row_start": pa.array([0], type=pa.int32()),
            "row_end": pa.array([0], type=pa.int32()),
            "ingested_at": [""],
            "thread_id": [""],
            # v2.0.29.4 (Phase 4 PR-2) — bootstrap row needs every
            # column declared in LANCEDB_SCHEMA or PyArrow's strict
            # schema validation rejects the table creation. NULL
            # means "no expiry" which is what we want for the
            # bootstrap row.
            "expires_at": [None],
        },
        schema=LANCEDB_SCHEMA,
    )
    table = db.create_table(TABLE_NAME, dummy, mode="overwrite")
    _ensure_fts_index(table)
    # Remove the bootstrap row
    try:
        table.delete("doc_id = '__bootstrap__'")
    except Exception:
        pass
    return table


def _maybe_add_thread_id_column(table) -> None:
    """Best-effort schema migration for tables created before the
    multi-conversation extension. If the column is missing, add it and
    backfill empty strings for every existing row.
    """
    try:
        existing_names = set(table.schema.names) if hasattr(table, "schema") else set()
    except Exception:
        existing_names = set()
    if not existing_names or "thread_id" in existing_names:
        return
    try:
        logger.info("Migrating LanceDB schema: adding thread_id column")
        table.add_columns([pa.field("thread_id", pa.string())])
        # Backfill every row with an empty string so existing chunks remain
        # globally visible until re-ingested under a thread scope.
        try:
            table.update(where=None, values={"thread_id": ""})
        except Exception as exc:  # pragma: no cover - version-dependent
            logger.warning(f"thread_id backfill failed (continuing): {exc}")
    except Exception as exc:
        logger.warning(f"thread_id column add failed (continuing): {exc}")


def _maybe_add_expires_at_column(table) -> None:
    """v2.0.29.4 (Phase 4 PR-2) — schema migration for ``expires_at``.

    Same pattern as ``_maybe_add_thread_id_column``: add the column
    to a pre-PR-2 table and backfill NULL (Python None, which LanceDB
    stores as ``null``) for every existing row. NULL means "no expiry"
    so legacy rows remain retrievable indefinitely.

    Idempotent: if the column already exists, this is a no-op.
    """
    try:
        existing_names = set(table.schema.names) if hasattr(table, "schema") else set()
    except Exception:
        existing_names = set()
    if not existing_names or "expires_at" in existing_names:
        return
    try:
        logger.info("Migrating LanceDB schema: adding expires_at column (Phase 4 PR-2)")
        table.add_columns([pa.field("expires_at", pa.string())])
        # No backfill needed — NULL is the "no expiry" default. Old rows
        # that lack ``expires_at`` simply read back as null and are not
        # filtered by ``_temporal_filter`` (which only excludes
        # ``expires_at <= now``). Distinct from the thread_id pattern
        # where empty-string-vs-null matters for the
        # ``thread_id = ''`` match.
    except Exception as exc:
        logger.warning(f"expires_at column add failed (continuing): {exc}")


def _ensure_fts_index(table) -> None:
    """Create the BM25 FTS index on the text column if missing."""
    try:
        existing = table.list_indices()
        has_fts = any("text" in str(idx.get("columns", [])) for idx in existing)
        if not has_fts:
            logger.info("Creating FTS index on 'text' column")
            try:
                # LanceDB 0.25+ API
                from lancedb.index import FTS  # type: ignore

                table.create_index("text", config=FTS(), replace=True)
            except Exception:
                # Older API fallback
                try:
                    table.create_fts_index("text", replace=True)
                except TypeError:
                    table.create_fts_index("text", use_tantivy=False, replace=True)
    except Exception as exc:  # pragma: no cover - depends on lance version
        logger.warning(f"Could not create FTS index (may already exist): {exc}")


def add_chunks(records: list[ChunkRecord]) -> None:
    """Append chunk records to LanceDB."""
    if not records:
        return
    table = get_table()
    rows = [r.to_lancedb_row() for r in records]
    table.add(rows, mode="append")
    logger.info(f"Indexed {len(rows)} chunks")
    # v2.0.10 — atomically flip each doc's registry status to "indexed"
    # IN THE SAME FUNCTION as the LanceDB write. Without this, the
    # Sidebar's ``pollUntilIndexed`` (which exits on ``cc > 0``) races
    # against the caller's next-line ``doc_registry.update("indexed")``:
    # chunks land → poll exits → sidebar's ``listDocuments`` sees the
    # registry still at "embedding" → "向量化中(N 块)" chip persists
    # indefinitely because the doc list has no auto-refresh hook after
    # upload completes.
    #
    # Co-locating the flip with the actual write means the polling's
    # ``cc > 0`` now also implies ``status === "indexed"``. The
    # caller's separate ``doc_registry.update("indexed")`` (the
    # historical v2.0.5 location) is now redundant — we no-op it.
    #
    # Wrapped in try/except so a registry hiccup (file lock, corrupt
    # JSON) doesn't fail the chunk write — chunks are already in
    # LanceDB and the next ``list_documents`` will surface them via
    # the default ``"indexed"`` fallback (see ``list_documents``),
    # so the worst case is a stale chip that refreshes in ≤5 s.
    try:
        from src.storage import doc_registry
        per_doc_count: dict[str, int] = {}
        for r in records:
            per_doc_count[r.doc_id] = per_doc_count.get(r.doc_id, 0) + 1
        for doc_id, n in per_doc_count.items():
            doc_registry.update(doc_id, status="indexed", chunk_count=n)
    except Exception as exc:
        logger.warning(f"add_chunks: registry status flip failed ({exc})")
    # Update the reverse index in lockstep — every doc_id gained at
    # least one new chunk, and the affected thread's per-thread cache
    # is now stale (new doc visible + counts changed).
    #
    # Use a set so multi-record uploads to one thread only invalidate
    # once. Capture filenames per (doc_id, thread_id) so the
    # per-thread ``first_filename`` can pick the EARLIEST-seen filename
    # for the title fallback (preserves the previous behavior of
    # ``list_threads_with_documents``).
    affected_threads: set[str] = set()
    for r in records:
        if not r.thread_id:
            continue
        affected_threads.add(r.thread_id)
        _doc_to_threads.setdefault(r.doc_id, set()).add(r.thread_id)
        _thread_to_docs.setdefault(r.thread_id, set()).add(r.doc_id)
        if r.thread_id not in _thread_first_filename:
            _thread_first_filename[r.thread_id] = r.filename
        # v2.0.6 P2-1 — bump the thread's latest-ingested-at to whichever
        # incoming record is more recent. ``ingested_at`` is an ISO 8601
        # ``...Z`` string, so plain string comparison gives chronological
        # order (we never mix timezones since ChunkRecord uses UTC).
        prev = _thread_latest_ingested_at.get(r.thread_id, "")
        if r.ingested_at and r.ingested_at > prev:
            _thread_latest_ingested_at[r.thread_id] = r.ingested_at
    for tid in affected_threads:
        invalidate_thread_doc_cache(tid)
        # v2.0.7 perf-3: also flush the per-thread chunk-list cache
        # so the next summary turn sees the new chunks.
        invalidate_thread_chunk_cache(tid)


def delete_by_doc_id(doc_id: str) -> int:
    """Delete all chunks belonging to a document. Returns rows deleted."""
    safe = _safe_identifier(doc_id, kind="doc_id")
    table = get_table()
    # Before deleting, capture which threads owned this doc so we can
    # invalidate THEIR caches only — not the entire cache. Without the
    # reverse index the previous code had to nuke all per-thread
    # caches (cheap, but cascades into spurious re-scans on every
    # unrelated thread's next turn).
    affected_threads = set(_doc_to_threads.get(safe, set()))
    try:
        # LanceDB's delete API uses a filter expression. We use the
        # double-equals form and a single-quoted literal — input is
        # validated to be hex-only above so it cannot break out of the
        # string.
        table.delete(f"doc_id = '{safe}'")
    except Exception:
        logger.exception(f"Delete by doc_id failed for {safe!r}")
        return 0
    # Drop the doc's reverse-index entry and shrink each affected
    # thread's per-thread set. If a thread's set goes empty, drop
    # both it AND its cached ``first_filename`` (an empty set means
    # the thread no longer has any indexed docs).
    _doc_to_threads.pop(safe, None)
    for tid in affected_threads:
        thread_docs = _thread_to_docs.get(tid)
        if thread_docs:
            thread_docs.discard(safe)
            if not thread_docs:
                _thread_to_docs.pop(tid, None)
                _thread_first_filename.pop(tid, None)
                # v2.0.6 P2-1 — no more docs in this thread, drop the
                # cached latest-ingested-at so a stale timestamp doesn't
                # outlive the thread's last document.
                _thread_latest_ingested_at.pop(tid, None)
        invalidate_thread_doc_cache(tid)
        # v2.0.7 perf-3: same rationale for the chunk-list cache.
        invalidate_thread_chunk_cache(tid)
    # LanceDB 0.18+ returns count; older versions don't
    return _count_by_doc(safe)


def _count_by_doc(doc_id: str) -> int:
    safe = _safe_identifier(doc_id, kind="doc_id")
    table = get_table()
    try:
        return table.count_rows(f"doc_id = '{safe}'")
    except Exception:
        logger.exception(f"count_rows failed for {safe!r}")
        return 0


def list_documents(thread_id: str | None = None) -> list[dict]:
    """Return a summary per indexed document (distinct doc_id).

    Merges two sources:

    1. The LanceDB chunk table — provides aggregated ``chunk_count`` and
       per-doc metadata for every doc that landed at least one chunk.
    2. The doc registry (``src.storage.doc_registry``) — supplies status
       (``pending`` / ``indexed`` / ``empty`` / ``failed``) and
       ``error_message`` for every registered doc, **including ones that
       produced zero chunks**. Without the registry, an "image-only" PDF
       that Docling's OCR couldn't read would silently vanish from the
       sidebar.

    When ``thread_id`` is provided and non-empty (validated), returns only
    documents that have at least one chunk tagged with that thread. The
    empty-string thread_id is the "globally visible" sentinel — rows
    without a thread scope — and is treated as visible to every caller
    when ``thread_id is None`` only (legacy behavior). When a caller
    explicitly passes a non-empty ``thread_id`` the filter restricts
    results to that thread alone. The registry merge applies the same
    filter so empty/failed docs are also scoped to the active thread.
    """
    table = get_table()
    arrow_tbl = None
    try:
        arrow_tbl = table.to_arrow()
    except Exception as exc:
        logger.warning(f"to_arrow failed: {exc}")
        # Not necessarily fatal — if the registry has entries we can
        # still surface those (e.g. a freshly-failed upload).

    import collections

    grouped: dict[str, dict] = collections.OrderedDict()

    if arrow_tbl is not None and arrow_tbl.num_rows > 0:
        col_names = (
            "doc_id",
            "filename",
            "source_type",
            "source_path",
            "ingested_at",
        )
        has_thread_col = "thread_id" in arrow_tbl.schema.names
        if has_thread_col:
            col_names = (*col_names, "thread_id")
        cols = {
            name: arrow_tbl.column(name).to_pylist() for name in col_names
        }
        for i, doc_id in enumerate(cols["doc_id"]):
            if not doc_id or doc_id == "__bootstrap__":
                continue
            row_tid = (
                cols.get("thread_id", [""] * (i + 1))[i]
                if has_thread_col
                else ""
            )
            # Filtering rules:
            #   thread_id=None  -> no filter (admin / legacy view)
            #   thread_id=set   -> only documents whose ANY chunk matches
            if thread_id is not None:
                safe = _safe_identifier(thread_id, kind="thread_id")
                if row_tid != safe:
                    continue
            if doc_id not in grouped:
                # v2.0.27 P0-P2: legacy LanceDB rows store the absolute
                # upload path. Coerce at read time to ``doc_id/filename``
                # so the wire surface stops leaking the server-side path.
                # ``_coerce_legacy_source_path`` is idempotent: new writes
                # already store the canonical form, so it's a no-op.
                from src.storage.doc_registry import _coerce_legacy_source_path

                row_filename = cols["filename"][i]
                row_source_path = cols["source_path"][i]
                coerced = _coerce_legacy_source_path(
                    row_source_path, doc_id, row_filename
                )
                grouped[doc_id] = {
                    "doc_id": doc_id,
                    "filename": row_filename,
                    "source_type": cols["source_type"][i],
                    "source_path": coerced,
                    "ingested_at": cols["ingested_at"][i],
                    "thread_id": row_tid,
                    "chunk_count": 0,
                    # Default to ``indexed`` for chunk-backed docs —
                    # the registry will overwrite if it has a fresher
                    # status (e.g. transient ``pending`` between upload
                    # and ingest completion).
                    "status": "indexed",
                    "error_message": None,
                }
            grouped[doc_id]["chunk_count"] += 1

    # Merge registry entries — this is the source of truth for
    # ``status`` / ``error_message`` and the ONLY source for docs that
    # produced zero chunks. Imported lazily so this module remains
    # importable without the registry sidecar (and so tests that mock
    # the registry don't pay an unrelated import cost).
    try:
        from src.storage import doc_registry

        registry = doc_registry.list_for_thread(thread_id)
    except Exception as e:
        logger.warning(f"list_documents: registry unavailable ({e})")
        registry = []

    for entry in registry:
        doc_id = entry["doc_id"]
        # Apply the same thread filter the chunk side already enforced.
        # ``list_for_thread`` above already filtered, but the entry's own
        # thread_id is also stored on the result for the API layer.
        if doc_id in grouped:
            # Already represented by chunks — let the registry override
            # status/error with the canonical value (it's set after
            # ingestion completes, so it's strictly newer / more
            # accurate than anything we'd infer from chunk count).
            grouped[doc_id]["status"] = entry.get("status", "indexed")
            grouped[doc_id]["error_message"] = entry.get("error_message")
            grouped[doc_id]["ingested_at"] = entry.get(
                "ingested_at", grouped[doc_id]["ingested_at"]
            )
            continue
        # Not in chunks: this is the empty/failed/pending case. Surface
        # it as-is so the user can see and delete the doc.
        # v2.0.27 P0-P2: post-migration the registry no longer carries a
        # ``source_path`` key. Derive the canonical privacy-safe value
        # from ``doc_id`` + ``filename`` (which we always have here).
        from src.storage.doc_registry import _serialize_source_path

        grouped[doc_id] = {
            "doc_id": doc_id,
            "filename": entry["filename"],
            "source_type": "file",
            "source_path": _serialize_source_path(
                "<synthesized>", doc_id, entry["filename"]
            ),
            "ingested_at": entry["ingested_at"],
            "thread_id": entry.get("thread_id", ""),
            "chunk_count": entry.get("chunk_count", 0),
            "status": entry.get("status", "empty"),
            "error_message": entry.get("error_message"),
        }
    return list(grouped.values())


def list_chunks_by_thread(thread_id: str, max_chunks: int = 100) -> list[dict]:
    """Return every chunk (text + metadata) for a given thread.

    Used by the "summarize / list / explain this document" retrieval
    path — when the user asks a meta question about their uploaded file
    rather than a semantic-content question, semantic search returns 0
    hits (because "总结这个文档" doesn't share embedding space with the
    document's body text). Returning every chunk of the thread's
    documents directly lets the LLM summarize the full content.

    The ``max_chunks`` cap protects against accidentally dumping a huge
    corpus into the prompt — 100 chunks is roughly 20-50 K tokens which
    is plenty for summarization but won't blow the context window.

    Returns ``[]`` for empty/invalid thread_id or on store failure. The
    caller falls back to standard hybrid retrieval in that case.
    """
    if not thread_id:
        return []
    try:
        safe = _safe_identifier(thread_id, kind="thread_id")
    except ValueError as exc:
        logger.warning(f"list_chunks_by_thread: unsafe thread_id ({exc}); skipping")
        return []
    table = get_table()
    try:
        arrow_tbl = table.to_arrow()
    except Exception as exc:
        logger.warning(f"list_chunks_by_thread: to_arrow failed: {exc}")
        return []
    if arrow_tbl.num_rows == 0:
        return []
    if "thread_id" not in arrow_tbl.schema.names:
        # Pre-migration table — every row is "globally visible", so the
        # safe approach is to refuse rather than leak other-thread rows.
        return []
    col_names = [
        "chunk_id",
        "doc_id",
        "text",
        "filename",
        "source_type",
        "chunk_index",
        "page_number",
        "section",
        "sheet",
    ]
    cols = {name: arrow_tbl.column(name).to_pylist() for name in col_names}
    out: list[dict] = []
    for i, row_tid in enumerate(arrow_tbl.column("thread_id").to_pylist()):
        if row_tid != safe:
            continue
        out.append(
            {
                "chunk_id": cols["chunk_id"][i],
                "doc_id": cols["doc_id"][i],
                "text": cols["text"][i],
                "filename": cols["filename"][i],
                "source_type": cols["source_type"][i],
                "chunk_index": cols["chunk_index"][i],
                "page_number": cols["page_number"][i],
                "section": cols["section"][i],
                "sheet": cols["sheet"][i],
            }
        )
        if len(out) >= max_chunks:
            break
    # Stable order: by doc_id then chunk_index, so the LLM sees a
    # logical progression through each document rather than a jumble.
    out.sort(key=lambda r: (r["doc_id"], r["chunk_index"]))
    return out


def delete_by_thread_id(thread_id: str) -> int:
    """Delete every chunk belonging to a thread. Returns rows deleted.

    Used by the sidebar's "delete conversation + docs" action. Validation
    uses the same banned-chars approach as ``_safe_identifier`` so a hostile
    thread_id cannot break out of the filter literal.
    """
    safe = _safe_identifier(thread_id, kind="thread_id")
    table = get_table()
    # Reverse-index cleanup BEFORE the delete: capture every doc_id
    # that this thread owned, drop them from the doc->threads index,
    # and drop the thread's own per-thread state.
    owned_docs = set(_thread_to_docs.pop(safe, set()))
    _thread_first_filename.pop(safe, None)
    for doc_id in owned_docs:
        edges = _doc_to_threads.get(doc_id)
        if edges:
            edges.discard(safe)
            if not edges:
                _doc_to_threads.pop(doc_id, None)
    try:
        table.delete(f"thread_id = '{safe}'")
    except Exception:
        logger.exception(f"Delete by thread_id failed for {safe!r}")
        return 0
    invalidate_thread_doc_cache(safe)
    # v2.0.7 perf-3: chunk-list cache too.
    invalidate_thread_chunk_cache(safe)
    try:
        return table.count_rows(f"thread_id = '{safe}'")
    except Exception:
        # count_rows isn't always available on older LanceDB; fall back to 0.
        return 0


def list_threads_with_documents() -> list[str]:
    """Return distinct non-empty thread_ids that have at least one chunk.

    Used by ``GET /sessions`` to surface threads in the sidebar even when
    the user uploaded documents but never sent a message (so no
    LangGraph checkpoint exists for them). Returns thread_ids in the
    order they first appear in the chunk table — ``/sessions`` re-sorts
    by updated_at so order here doesn't matter for display.

    Empty-string thread_id rows are excluded (the globally-visible
    sentinel isn't a real conversation). Returns ``[]`` on store error
    or when the table has no rows.
    """
    table = get_table()
    try:
        arrow_tbl = table.to_arrow()
    except Exception as exc:
        logger.warning(f"list_threads_with_documents: to_arrow failed: {exc}")
        return []
    if arrow_tbl.num_rows == 0:
        return []
    if "thread_id" not in arrow_tbl.schema.names:
        return []
    seen: set[str] = set()
    out: list[str] = []
    for tid in arrow_tbl.column("thread_id").to_pylist():
        if not tid or tid in seen:
            continue
        seen.add(tid)
        out.append(tid)
    return out


# ----------------------------------------------------------------------
# Reverse index maintenance + count_documents_by_threads
# ----------------------------------------------------------------------


def _build_reverse_index_from_disk() -> None:
    """Populate the reverse index from a single LanceDB scan.

    Called lazily on the first ``count_documents_by_threads`` call, and
    on every ``reset_for_tests``. Subsequent mutations are maintained
    incrementally (``add_chunks`` / ``delete_by_doc_id`` /
    ``delete_by_thread_id`` each update the relevant slices).

    Tolerates failures: a corrupt / empty table just leaves the index
    empty and the next mutation rebuilds it.
    """
    with _reverse_index_lock:
        _doc_to_threads.clear()
        _thread_to_docs.clear()
        _thread_first_filename.clear()
        _thread_latest_ingested_at.clear()
    try:
        table = get_table()
        arrow_tbl = table.to_arrow()
        if arrow_tbl.num_rows == 0 or "thread_id" not in arrow_tbl.schema.names:
            return
        doc_ids = arrow_tbl.column("doc_id").to_pylist()
        tids = arrow_tbl.column("thread_id").to_pylist()
        filenames = arrow_tbl.column("filename").to_pylist()
        # v2.0.6 P2-1 — also read ``ingested_at`` so we can build the
        # per-thread max timestamp in one pass alongside the rest of
        # the index. Older tables (pre-2.0.6) may lack the column.
        ingested_ats: list[str] = []
        if "ingested_at" in arrow_tbl.schema.names:
            ingested_ats = arrow_tbl.column("ingested_at").to_pylist()
        with _reverse_index_lock:
            for idx, (doc_id, tid, fname) in enumerate(
                zip(doc_ids, tids, filenames)
            ):
                if not doc_id or doc_id == "__bootstrap__":
                    continue
                if not tid:
                    continue
                _doc_to_threads.setdefault(doc_id, set()).add(tid)
                _thread_to_docs.setdefault(tid, set()).add(doc_id)
                if tid not in _thread_first_filename:
                    _thread_first_filename[tid] = fname
                # Maintain max — ISO 8601 strings sort lexicographically
                # the same as chronologically when they share the ``Z``
                # suffix that ``ChunkRecord.ingested_at`` produces.
                if ingested_ats:
                    cur_ts = ingested_ats[idx]
                    if cur_ts:
                        prev = _thread_latest_ingested_at.get(tid, "")
                        if cur_ts > prev:
                            _thread_latest_ingested_at[tid] = cur_ts
    except Exception as exc:
        logger.warning(f"reverse index build failed: {exc}")


def count_documents_by_threads(
    tids: Iterable[str],
) -> dict[str, tuple[int, str]]:
    """For each requested thread_id, return ``(distinct_doc_count, first_filename)``.

    This is the N+1 fix for ``GET /sessions``. The previous code called
    ``list_documents(thread_id=tid)`` inside a loop over every session,
    each invocation doing a full LanceDB ``to_arrow()`` scan. For a
    user with 50 conversations this was 50 scans (~50×100 ms = ~5 s)
    every time the sidebar loaded. This function does ONE scan total
    (or zero scans if the reverse index is already warm) and returns
    per-thread aggregates as O(1) dict reads.

    Returns ``(0, "")`` for threads that have no indexed docs —
    identical to the previous behavior where ``list_documents`` would
    return an empty list.
    """
    # Build / refresh the reverse index on first use. After that, every
    # mutation (add_chunks / delete_by_doc_id / delete_by_thread_id)
    # keeps it in sync incrementally, so subsequent calls are pure
    # dict reads — no LanceDB scan at all.
    if not _thread_to_docs and not _doc_to_threads:
        _build_reverse_index_from_disk()
    with _reverse_index_lock:
        out: dict[str, tuple[int, str]] = {}
        for tid in tids:
            docs = _thread_to_docs.get(tid, set())
            out[tid] = (len(docs), _thread_first_filename.get(tid, ""))
        return out


def latest_ingested_at_by_threads(tids: Iterable[str]) -> dict[str, str]:
    """For each requested thread_id, return the most recent ``ingested_at``
    ISO 8601 string across all chunks owned by that thread.

    Empty string when the thread has no indexed chunks (matches the
    pre-v2.0.6 wire contract for threads with zero docs — the sidebar
    falls back to whatever else it has for sorting).

    v2.0.6 P2-1 — ``GET /sessions`` doc-only threads used to return
    ``updated_at=""`` because there was no LangGraph checkpoint to read
    from. With this helper the route populates ``updated_at`` from
    ``max(ingested_at)`` instead, so doc-only threads sort correctly
    in the sidebar.

    Like :func:`count_documents_by_threads` this is O(1) dict reads
    once the reverse index is warm — no per-thread LanceDB scan.
    """
    if not _thread_to_docs and not _doc_to_threads:
        _build_reverse_index_from_disk()
    with _reverse_index_lock:
        return {
            tid: _thread_latest_ingested_at.get(tid, "") for tid in tids
        }


__all__ = [
    "get_db",
    "get_table",
    "add_chunks",
    "count_documents_by_threads",
    "delete_by_doc_id",
    "delete_by_thread_id",
    "latest_ingested_at_by_threads",
    "list_documents",
    "list_documents_cached",
    "list_chunks_by_thread",
    "list_chunks_by_thread_cached",
    "list_threads_with_documents",
    "invalidate_thread_doc_cache",
    "invalidate_thread_chunk_cache",
    "reset_for_tests",
]


# ----------------------------------------------------------------------
# TTL cache for list_documents(thread_id)
# ----------------------------------------------------------------------
# Why this exists
# ----------------
# ``list_documents`` is the per-turn ``route_query`` hook. It runs a
# full LanceDB ``to_arrow()`` scan plus a Python group-by on every chat
# turn that isn't an obvious greeting (so basically every "real"
# question). Measured at 30-200 ms / call on a thread with hundreds of
# chunks. Caching the per-thread result for a few seconds collapses the
# per-turn cost of conversational follow-ups to ~0 ms — the cheap
# routing LLM only needs the same document list the previous turn
# produced.
#
# Why TTL instead of strict invalidation
# --------------------------------------
# Strict invalidation would need to fire on:
#   - every doc-registry status transition (pending→indexed, etc.)
#   - every chunk add (we do invalidate here)
#   - every doc delete (we do invalidate here)
#   - every thread delete (we do invalidate here)
# But status transitions are noisy (the registry flips between
# states many times during a single upload), and they don't actually
# change what the routing LLM needs to know (filenames + a count).
# A 5-second TTL means the worst-case staleness window is bounded
# AND we can be loose about which registry events invalidate. The
# big correctness-critical events (chunks landing, doc deleted) still
# invalidate synchronously.

_THREAD_DOC_CACHE_TTL_SEC = 5.0
_thread_doc_cache: dict[str, tuple[float, list[dict]]] = {}
_thread_doc_cache_lock = threading.Lock()

# v2.0.7 perf-3: separate TTL cache for ``list_chunks_by_thread``,
# which is called on every summary-intent turn by the agent's
# ``summary`` path. With a 50 K-chunk corpus the full scan was costing
# 200-500 ms per summary turn — see the perf survey. TTL is set
# longer than the doc cache (30 s vs 5 s) because summary reads
# dominate the write rate during the relevant window and stale
# chunks do not change the answer materially until the user
# uploads more files.
_THREAD_CHUNK_CACHE_TTL_SEC = 30.0
_thread_chunk_cache: dict[str, tuple[float, list[dict]]] = {}
_thread_chunk_cache_lock = threading.Lock()


def list_documents_cached(thread_id: str | None) -> list[dict]:
    """Cache front for :func:`list_documents` keyed by ``thread_id``
    with a 5-second TTL.

    Use this on the chat / routing hot path where the calling code
    only needs to know "what docs does this thread have" and can
    tolerate a few seconds of staleness. Use :func:`list_documents`
    directly when you need a fresh read (e.g. the docs-list endpoint
    that powers the sidebar — the user expects immediate feedback
    after a delete).

    Returns the cached value if it exists and is younger than the TTL,
    otherwise calls :func:`list_documents` and stores the result.

    Thread-safe: the lookup + insert pair is serialized with a lock so
    two concurrent callers can't both observe an empty cache and both
    run the full scan.
    """
    key = thread_id if thread_id else "__no_thread__"
    now = time.monotonic()
    with _thread_doc_cache_lock:
        cached = _thread_doc_cache.get(key)
        if cached is not None:
            ts, value = cached
            if now - ts < _THREAD_DOC_CACHE_TTL_SEC:
                return value
    value = list_documents(thread_id=thread_id)
    with _thread_doc_cache_lock:
        _thread_doc_cache[key] = (now, value)
    return value


def invalidate_thread_doc_cache(thread_id: str | None = None) -> None:
    """Drop one thread's cached ``list_documents`` result, or all of them.

    Pass ``thread_id`` to drop just that thread (used by ``add_chunks``
    and ``delete_by_thread_id``). Pass ``None`` (the default) to clear
    the entire cache — used by ``delete_by_doc_id`` (we don't know
    which thread the doc belonged to without another scan) and by
    ``reset_for_tests``.
    """
    with _thread_doc_cache_lock:
        if thread_id is None:
            _thread_doc_cache.clear()
            return
        _thread_doc_cache.pop(thread_id if thread_id else "__no_thread__", None)


def list_chunks_by_thread_cached(thread_id: str | None) -> list[dict]:
    """Cache front for :func:`list_chunks_by_thread` keyed by ``thread_id``
    with a 30-second TTL.

    v2.0.7 perf-3 — mirrors :func:`list_documents_cached` for the
    summary-intent hot path. The summary turn flow (see
    ``src/agent/nodes/retrieve.py``) calls ``list_chunks_by_thread``
    on every invocation; on a 50 K-chunk corpus this was a 200-500 ms
    full scan per turn. Caching saves the scan when the corpus
    hasn't changed within the TTL window.

    Use this on the summary / chat hot path. Use
    :func:`list_chunks_by_thread` directly when you need a fresh
    read (e.g. right after a delete where staleness would be
    user-visible).
    """
    key = thread_id if thread_id else "__no_thread__"
    now = time.monotonic()
    with _thread_chunk_cache_lock:
        cached = _thread_chunk_cache.get(key)
        if cached is not None:
            ts, value = cached
            if now - ts < _THREAD_CHUNK_CACHE_TTL_SEC:
                return value
    value = list_chunks_by_thread(thread_id=thread_id)
    with _thread_chunk_cache_lock:
        _thread_chunk_cache[key] = (now, value)
    return value


def invalidate_thread_chunk_cache(thread_id: str | None = None) -> None:
    """Drop one thread's cached ``list_chunks_by_thread`` result.

    Pass ``thread_id`` to drop just that thread; pass ``None`` to
    clear every entry. Same invalidation contract as
    :func:`invalidate_thread_doc_cache`.
    """
    with _thread_chunk_cache_lock:
        if thread_id is None:
            _thread_chunk_cache.clear()
            return
        _thread_chunk_cache.pop(thread_id if thread_id else "__no_thread__", None)
